## INTRODUCTION TO NUMPY
### Importation of Numpy

In [21]:
import numpy as np

### Creation of Arrays using Numpy

In [25]:
a = np.array([1, 2, 3, 4, 5])

In [27]:
a

array([1, 2, 3, 4, 5])

In [36]:
b = np.array(1)

In [38]:
b

array(1)

In [42]:
c = np.array([1, True, "Carol", "Nairobi"])

In [44]:
c

array(['1', 'True', 'Carol', 'Nairobi'], dtype='<U11')

### Dimensions in Arrays

In [49]:
a.ndim

1

In [51]:
d = np.array([[1,2], [3,4]]) 
d.ndim

2

In [65]:
e = np.array([[[1, 2], [3, 4]], [[5,6], [7,8]]])

In [67]:
e.ndim

3

### Creation of Special Arrays

In [70]:
f = np.zeros(6)

In [72]:
f

array([0., 0., 0., 0., 0., 0.])

In [74]:
g = np.ones(6)

In [76]:
g

array([1., 1., 1., 1., 1., 1.])

In [93]:
h = np.zeros((3,3))

In [95]:
h

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [97]:
i = np.ones((3,3))

In [99]:
i

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
j = np.full((4,4), 2)

In [109]:
j

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [111]:
k = np.full((4,4), "Carol")

In [113]:
k

array([['Carol', 'Carol', 'Carol', 'Carol'],
       ['Carol', 'Carol', 'Carol', 'Carol'],
       ['Carol', 'Carol', 'Carol', 'Carol'],
       ['Carol', 'Carol', 'Carol', 'Carol']], dtype='<U5')